<#
.SYNOPSIS
A wizard walks a human through a manual procedure, step by step (PowerShell Edition).
Generated by the /wizard skill.

Everything above the "STAGES" marker is the wizard library: do not hand-edit it.
Author the per-step stages below the marker.
#>

$ErrorActionPreference = 'Stop'

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

$script:TotalStages = 0
$script:StageIndex = 0
$script:EnvFile = if ($env:ENV_FILE) { $env:ENV_FILE } else { '.env' }
$script:WrittenEnv = [System.Collections.Generic.List[string]]::new()
$script:WrittenSecret = [System.Collections.Generic.List[string]]::new()
$script:Skipped = [System.Collections.Generic.List[string]]::new()

function Clear-WizardScreen {
    if ([Environment]::UserInteractive) {
        Clear-Host
    }
}

function Show-Banner([string]$Title) {
    Clear-WizardScreen
    Write-Host "`n  $Title" -ForegroundColor Cyan
    Write-Host "  $script:TotalStages stages`n" -ForegroundColor DarkGray
    Write-Host "  You drive the browser; this wizard tells you exactly what to do and" -ForegroundColor DarkGray
    Write-Host "  captures the values you copy back. Stop any time with Ctrl-C and re-run" -ForegroundColor DarkGray
    Write-Host "  later, since it remembers values already saved." -ForegroundColor DarkGray
    Pause-Wizard "Ready to start?"
}

function Show-Stage([string]$Name) {
    Clear-WizardScreen
    $script:StageIndex++
    Write-Host "`n▸ Stage $script:StageIndex/$script:TotalStages · $Name" -ForegroundColor Cyan
}

function Say([string]$Text) {
    Write-Host "  $Text"
}

function Step([string]$Text) {
    Write-Host "  " -NoNewline
    Write-Host "•" -ForegroundColor Cyan -NoNewline
    Write-Host " $Text"
}

function Note([string]$Text) {
    Write-Host "  $Text" -ForegroundColor DarkGray
}

function Warn([string]$Text) {
    Write-Host "  ⚠ $Text" -ForegroundColor Yellow
}

function Open-Url([string]$Url) {
    Write-Host "  " -NoNewline
    Write-Host "↗ opening" -ForegroundColor Green -NoNewline
    Write-Host " $Url"
    try {
        Start-Process $Url
    } catch {
        Warn "couldn't open a browser; visit it manually: $Url"
    }
}

function Pause-Wizard([string]$Message = "Press Enter to continue") {
    Write-Host "  $Message " -ForegroundColor DarkGray -NoNewline
    [void][System.Console]::ReadLine()
}

function Confirm-Wizard([string]$Question) {
    Write-Host "  ? $Question [y/N] " -ForegroundColor Yellow -NoNewline
    $reply = [System.Console]::ReadLine()
    return ($reply -match '^[Yy]')
}

function Get-ExistingEnv([string]$Key) {
    if (-not (Test-Path $script:EnvFile)) { return $null }
    $match = Get-Content $script:EnvFile | Where-Object { $_ -match "^$Key=(.*)$" } | Select-Object -Last 1
    if ($match -match "^$Key=(.*)$") {
        return $matches[1]
    }
    return $null
}

function Ask-Value([string]$Key, [string]$Prompt) {
    $current = Get-ExistingEnv $Key
    if ($current) {
        Write-Host "  $Prompt " -NoNewline
        Write-Host "[Enter keeps current] " -ForegroundColor DarkGray -NoNewline
    } else {
        Write-Host "  $Prompt " -NoNewline
    }
    $inputVal = [System.Console]::ReadLine()
    if ([string]::IsNullOrWhiteSpace($inputVal) -and $current) {
        $inputVal = $current
    }
    Set-Variable -Name $Key -Value $inputVal -Scope Script
    return $inputVal
}

function Ask-SecretValue([string]$Key, [string]$Prompt) {
    $current = Get-ExistingEnv $Key
    if ($current) {
        Write-Host "  $Prompt " -NoNewline
        Write-Host "[Enter keeps current] " -ForegroundColor DarkGray -NoNewline
    } else {
        Write-Host "  $Prompt " -NoNewline
    }
    
    $secure = Read-Host -AsSecureString
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    $inputVal = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
    [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    
    if ([string]::IsNullOrWhiteSpace($inputVal) -and $current) {
        $inputVal = $current
    }
    Set-Variable -Name $Key -Value $inputVal -Scope Script
    return $inputVal
}

function Write-EnvFile([string]$Key, [string]$Value) {
    if (-not (Test-Path $script:EnvFile)) {
        New-Item -ItemType File -Path $script:EnvFile -Force | Out-Null
    }
    $lines = @()
    if (Test-Path $script:EnvFile) {
        $lines = Get-Content $script:EnvFile | Where-Object { $_ -notmatch "^$Key=" }
    }
    $lines += "$Key=$Value"
    Set-Content -Path $script:EnvFile -Value $lines -Encoding utf8
    $script:WrittenEnv.Add($Key)
    Write-Host "  " -NoNewline
    Write-Host "✓ wrote" -ForegroundColor Green -NoNewline
    Write-Host " $Key → $script:EnvFile"
}

function Set-GhSecret([string]$Name, [string]$Value) {
    $ghAvailable = (Get-Command gh -ErrorAction SilentlyContinue)
    if ($ghAvailable) {
        try {
            $Value | gh secret set $Name 2>$null
            if ($LASTEXITCODE -eq 0) {
                $script:WrittenSecret.Add($Name)
                Write-Host "  " -NoNewline
                Write-Host "✓ set" -ForegroundColor Green -NoNewline
                Write-Host " GitHub secret $Name"
                return
            }
        } catch { }
    }
    $script:Skipped.Add("GitHub secret $Name (set it manually: gh secret set $Name)")
    Warn "skipped GitHub secret $Name: gh not ready; set it later"
}

function Set-GhVar([string]$Name, [string]$Value) {
    $ghAvailable = (Get-Command gh -ErrorAction SilentlyContinue)
    if ($ghAvailable) {
        try {
            gh variable set $Name --body $Value 2>$null
            if ($LASTEXITCODE -eq 0) {
                Write-Host "  " -NoNewline
                Write-Host "✓ set" -ForegroundColor Green -NoNewline
                Write-Host " GitHub variable $Name"
                return
            }
        } catch { }
    }
    $script:Skipped.Add("GitHub variable $Name")
    Warn "skipped GitHub variable $Name, gh not ready; set it later"
}

function Finish-Wizard {
    Clear-WizardScreen
    Write-Host "`n  ✓ Setup complete" -ForegroundColor Green
    if ($script:WrittenEnv.Count -gt 0) {
        Note "wrote $($script:WrittenEnv.Count) value(s) to $script:EnvFile`: $($script:WrittenEnv -join ', ')"
    }
    if ($script:WrittenSecret.Count -gt 0) {
        Note "set $($script:WrittenSecret.Count) GitHub secret(s): $($script:WrittenSecret -join ', ')"
    }
    if ($script:Skipped.Count -gt 0) {
        Write-Host ""
        Warn "still to do by hand:"
        foreach ($s in $script:Skipped) {
            Note "  - $s"
        }
    }
    Write-Host ""
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage per step the human takes.
# Replace the example below. Set $script:TotalStages to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

$script:TotalStages = 1

Show-Banner "Stripe setup"

# ── Example stage: replace with your real steps ───────────────────────────
Show-Stage "Stripe: API keys"
Say "We'll grab your Stripe test keys and store them for local dev + CI."
Open-Url "https://dashboard.stripe.com/test/apikeys"
Step "On the API keys page, copy the Publishable key (starts pk_test_)."
Ask-Value "STRIPE_PUBLISHABLE_KEY" "Paste the publishable key:"
Step "Click 'Reveal test key' on the Secret key row, then copy it."
Ask-SecretValue "STRIPE_SECRET_KEY" "Paste the secret key:"
Write-EnvFile "STRIPE_PUBLISHABLE_KEY" $script:STRIPE_PUBLISHABLE_KEY
Write-EnvFile "STRIPE_SECRET_KEY" $script:STRIPE_SECRET_KEY
Set-GhSecret "STRIPE_SECRET_KEY" $script:STRIPE_SECRET_KEY   # CI needs this one
# ──────────────────────────────────────────────────────────────────────────

Finish-Wizard
